spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring6
    username: root
    password: wzh7230610
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: user
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
#    type: com.zaxxer.hikari.HikariDataSource

