#spring:
#  mvc:
#    # 静态资源访问的页面前缀，设置之后springboot默认访问的index页面、favicon.ico都会失效
#    static-path-pattern: /res/**
#
#  web:
#    resources:
#      # 配置静态资源路径，可以配置多个，用逗号隔开
#      static-locations: classpath:/hahaha
spring:
  mvc:
    hidden-method:
      filter:
        enabled: true