# yaml
person:
  boss: false
  birth: 2023/10/8 20:12:33
  age: 20
  pet:
    name: tomcat
    weight: 23.4
  interests: [ "唱", "跳", rap, "篮球" ]
  animal:
    - jerry
    - mario
  score:
    english:
      first: 30
      second: 40
      third: 50
    math: [ 131, 140, 148 ]
    chinese: { first: 30, second: 40, third: 50 }
  salarys: [ 1000, 2000, 3000, 4000 ]
  allPets:
    sick:
      - { name: tom }
      - { name: jerry, weight: 47 }
    health: [ { name: mario, weight: 47 } ]
  user-name: zhangsan

